version: 0.2

phases:
  install:
    commands:
      - echo Installing Node.js dependencies...
      - npm install

  pre_build:
    commands:
      - echo Pre-build phase started...

  build:
    commands:
      - echo Running build command...
      - npm run build

  post_build:
    commands:
      - echo Build completed. Checking dist folder...
      - ls -R dist/   # <-- THIS WILL SHOW YOU THE REAL OUTPUT PATH
      - echo Uploading to S3 Bucket...
      - aws s3 sync dist/ s3://rakesh-55/ --delete --region ap-south-1
      - echo Upload finished successfully.

artifacts:
  files:
    - '**/*'
  base-directory: dist
  discard-paths: no
